// <auto-generated />
using System;
using System.Text.Json;
using AgendaPlus.Domain.Entities;
using AgendaPlus.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AgendaPlus.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260212195143_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AgendaPlus.Domain.Entities.AuthToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<int>("LoginFailedAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("failed_attempts");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("text")
                        .HasColumnName("password_reset_token");

                    b.Property<DateTime?>("PasswordResetTokenExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("password_reset_token_expires_at");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text")
                        .HasColumnName("refresh_token");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_auth_tokens");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_auth_tokens_tenant_id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_auth_tokens_user_id");

                    b.ToTable("auth_tokens", (string)null);
                });

            modelBuilder.Entity("AgendaPlus.Domain.Entities.AvailabilityExceptions", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("EndBlockTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_block_time");

                    b.Property<TimeOnly?>("OverrideEndTime")
                        .HasColumnType("time")
                        .HasColumnName("new_end_time");

                    b.Property<TimeOnly?>("OverrideStartTime")
                        .HasColumnType("time")
                        .HasColumnName("new_start_time");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("new_price_per_hour");

                    b.Property<string>("Reason")
                        .HasColumnType("varchar(500)")
                        .HasColumnName("reason");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("resource_id");

                    b.Property<DateTime>("StartBlockTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_block_time");

                    b.Property<short>("Strategy")
                        .HasColumnType("smallint")
                        .HasColumnName("strategy");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_availability_exceptions");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_availability_exceptions_tenant_id");

                    b.ToTable("availability_exceptions", null, t =>
                        {
                            t.HasCheckConstraint("chk_strategy_logic", "(strategy = 0) OR (strategy = 1 AND new_start_time IS NOT NULL AND new_end_time IS NOT NULL) OR (strategy = 2 AND new_price_per_hour IS NOT NULL) OR (strategy = 3 AND new_start_time IS NOT NULL AND new_end_time IS NOT NULL AND new_price_per_hour IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("AgendaPlus.Domain.Entities.AvailabilityPatterns", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer")
                        .HasColumnName("day_of_week");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("end_time");

                    b.Property<decimal>("PricePerHour")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("price_per_hour");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("resource_id");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("start_time");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_availability_patterns");

                    b.HasIndex("ResourceId")
                        .HasDatabaseName("ix_availability_patterns_resource_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("idx_availability_patterns_tenant");

                    b.ToTable("availability_patterns", null, t =>
                        {
                            t.HasCheckConstraint("chk_endTime_greater_startTime", "end_time > start_time");
                        });
                });

            modelBuilder.Entity("AgendaPlus.Domain.Entities.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("EndBookingDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_booking_date_time");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("resource_id");

                    b.Property<DateTime>("StartBookingDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_booking_date_time");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("total_price");

                    b.Property<DateTimeOffset>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("pk_bookings");

                    b.HasIndex("ResourceId")
                        .HasDatabaseName("ix_bookings_resource_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("idx_bookings_tenant");

                    b.ToTable("bookings", null, t =>
                        {
                            t.HasCheckConstraint("chk_booking_time_logic", "end_booking_date_time > start_booking_date_time");
                        });
                });

            modelBuilder.Entity("AgendaPlus.Domain.Entities.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<JsonDocument>("Content")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTimeOffset>("OccurredOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTimeOffset?>("ProcessedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("AgendaPlus.Domain.Entities.Resource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.Property<int>("OpenDays")
                        .HasColumnType("integer")
                        .HasColumnName("open_days");

                    b.Property<int>("ResourceType")
                        .HasColumnType("integer")
                        .HasColumnName("resource_type");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_resources");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("idx_resources_tenant");

                    b.ToTable("resources", null, t =>
                        {
                            t.HasCheckConstraint("chk_openDays_positive", "open_days >= 0");
                        });
                });

            modelBuilder.Entity("AgendaPlus.Domain.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<TenantSettings>("Settings")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("settings")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("time_zone");

                    b.HasKey("Id")
                        .HasName("pk_tenants");

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("AgendaPlus.Domain.Entities.TenantAdress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasColumnType("varchar(15)")
                        .HasColumnName("cep");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("city_name");

                    b.Property<string>("CountryCodeAlpha2")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(2)")
                        .HasDefaultValue("BR")
                        .HasColumnName("country_code_alpha2");

                    b.Property<string>("GooglePlaceId")
                        .HasColumnType("varchar(500)")
                        .HasColumnName("google_place_id");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(10,8)")
                        .HasColumnName("latitude");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(11,8)")
                        .HasColumnName("longitude");

                    b.Property<string>("Number")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("number");

                    b.Property<string>("StateCode")
                        .IsRequired()
                        .HasColumnType("varchar(5)")
                        .HasColumnName("state_code");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasColumnName("street");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_tenants_adress");

                    b.HasIndex("Cep")
                        .IsUnique()
                        .HasDatabaseName("ix_tenants_adress_cep");

                    b.HasIndex("GooglePlaceId")
                        .HasDatabaseName("ix_tenants_adress_google_place_id");

                    b.HasIndex("TenantId")
                        .IsUnique()
                        .HasDatabaseName("ix_tenants_adress_tenant_id");

                    b.HasIndex("Latitude", "Longitude")
                        .HasDatabaseName("ix_tenants_adress_latitude_longitude");

                    b.HasIndex("StateCode", "CityName")
                        .HasDatabaseName("ix_tenants_adress_state_code_city_name");

                    b.ToTable("tenants_adress", (string)null);
                });

            modelBuilder.Entity("AgendaPlus.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_active");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<short>("Role")
                        .HasColumnType("smallint")
                        .HasColumnName("role");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("idx_users_email");

                    b.HasIndex("TenantId", "Email")
                        .IsUnique()
                        .HasDatabaseName("idx_users_tenant_email");

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("chk_users_role", "role IN (0, 1, 2)");
                        });
                });

            modelBuilder.Entity("AgendaPlus.Domain.Entities.UserTenant", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.HasKey("UserId", "TenantId")
                        .HasName("pk_user_tenants");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_user_tenants_tenant_id");

                    b.ToTable("user_tenants", (string)null);
                });

            modelBuilder.Entity("AgendaPlus.Domain.Entities.AuthToken", b =>
                {
                    b.HasOne("AgendaPlus.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_auth_tokens_tenants_tenant_id");

                    b.HasOne("AgendaPlus.Domain.Entities.User", "User")
                        .WithOne("Token")
                        .HasForeignKey("AgendaPlus.Domain.Entities.AuthToken", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_auth_tokens_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AgendaPlus.Domain.Entities.AvailabilityExceptions", b =>
                {
                    b.HasOne("AgendaPlus.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_availability_exceptions_tenants_tenant_id");
                });

            modelBuilder.Entity("AgendaPlus.Domain.Entities.AvailabilityPatterns", b =>
                {
                    b.HasOne("AgendaPlus.Domain.Entities.Resource", "Resource")
                        .WithMany()
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_availability_patterns_resources_resource_id");

                    b.HasOne("AgendaPlus.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_availability_patterns_tenants_tenant_id");

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("AgendaPlus.Domain.Entities.Booking", b =>
                {
                    b.HasOne("AgendaPlus.Domain.Entities.Resource", "Resource")
                        .WithMany("Bookings")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bookings_resources_resource_id");

                    b.HasOne("AgendaPlus.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bookings_tenants_tenant_id");

                    b.OwnsOne("AgendaPlus.Domain.Entities.CustomerData", "CustomerData", b1 =>
                        {
                            b1.Property<Guid>("BookingId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("Email")
                                .HasColumnType("text");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("PhoneNumber")
                                .HasColumnType("text");

                            b1.HasKey("BookingId");

                            b1.ToTable("bookings");

                            b1.ToJson("customer_data");

                            b1.WithOwner()
                                .HasForeignKey("BookingId")
                                .HasConstraintName("fk_bookings_bookings_id");
                        });

                    b.Navigation("CustomerData")
                        .IsRequired();

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("AgendaPlus.Domain.Entities.Resource", b =>
                {
                    b.HasOne("AgendaPlus.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_resources_tenants_tenant_id");
                });

            modelBuilder.Entity("AgendaPlus.Domain.Entities.TenantAdress", b =>
                {
                    b.HasOne("AgendaPlus.Domain.Entities.Tenant", "Tenant")
                        .WithOne("Adress")
                        .HasForeignKey("AgendaPlus.Domain.Entities.TenantAdress", "TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tenants_adress_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("AgendaPlus.Domain.Entities.User", b =>
                {
                    b.HasOne("AgendaPlus.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_users_tenants_tenant_id");
                });

            modelBuilder.Entity("AgendaPlus.Domain.Entities.UserTenant", b =>
                {
                    b.HasOne("AgendaPlus.Domain.Entities.Tenant", "Tenant")
                        .WithMany("UserTenants")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_tenants_tenants_tenant_id");

                    b.HasOne("AgendaPlus.Domain.Entities.User", "User")
                        .WithMany("UserTenants")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_tenants_users_user_id");

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AgendaPlus.Domain.Entities.Resource", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("AgendaPlus.Domain.Entities.Tenant", b =>
                {
                    b.Navigation("Adress")
                        .IsRequired();

                    b.Navigation("UserTenants");
                });

            modelBuilder.Entity("AgendaPlus.Domain.Entities.User", b =>
                {
                    b.Navigation("Token");

                    b.Navigation("UserTenants");
                });
#pragma warning restore 612, 618
        }
    }
}
